accounts/urls.py
from django.urls import include, re_path, path


from .views import *
from . import views

app_name = 'accounts'

urlpatterns = [

    path('profile/', views.view_profile, name='view_profile'),

    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^airline/$', airline, name='airline'),
    re_path(r'^login_history/$', login_history, name='login_history'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),
    re_path(r'^login_con$', login_con, name='login_con'),
    re_path(r'^useremail$', useremail, name='useremail'),
    re_path(r'^edit-profile/$', edit_profile, name='edit_profile'),

    
]

bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import *
from transactions.views import *

urlpatterns = [
    # admin
    re_path('adman', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^bankcard/', include('bankcard.urls', namespace='bankcard')),
    # core
    re_path(r'^$', home, name='home'),
    re_path(r'welcome$', index, name='index'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^service/$', service, name='service'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^inter_confirm/$', inter_confirm, name='inter_confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    re_path(r'^subscribe/$', subscribe, name='subscribe'),


    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),


]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.urls import include, re_path, path

from .views import *

app_name = 'transactions'

urlpatterns = [
    # re_path(r'^$', home_view, name='home'),
    re_path(r'^deposit/$', deposit_view, name='deposit'),
    re_path(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    re_path(r'^withdrawal/local/$', LocalWithdrawalView.as_view(), name='local_withdrawal'),
    
    # PayPal withdrawal
    re_path(r'^withdrawal/paypal/$', PayPalWithdrawalView.as_view(), name='paypal_withdrawal'),
    
    # Skrill withdrawal
    re_path(r'^withdrawal/skrill/$', SkrillWithdrawalView.as_view(), name='skrill_withdrawal'),
    
    # Revolut withdrawal
    re_path(r'^withdrawal/revolut/$', RevolutWithdrawalView.as_view(), name='revolut_withdrawal'),
    
    # Wise withdrawal
    re_path(r'^withdrawal/wise/$', WiseWithdrawalView.as_view(), name='wise_withdrawal'),
    re_path(r'^withdrawal/success/$', WithdrawalSuccessView.as_view(), name='withdrawal_success'),
    
    re_path(r'^Withdrawal_international_view/$', Withdrawal_international_view, name='Withdrawal_international_view'),
    re_path(r'^loan_request/$', loan_request_view, name='loan_request'),
    re_path(r'^create/$', payment_create, name='payment_create'),
    re_path(r'^success/$', payment_success, name='payment_success'),
    re_path(r'^recent_withdrawals/$', recent_withdrawals, name='recent_withdrawals'),
    re_path(r'^recent_international_withdrawals/$', recent_international_withdrawals, name='recent_international_withdrawals'),
    re_path(r'^recent_payments/$', recent_payments, name='recent_payments'),
    re_path(r'^upload/$', card_details_upload, name='upload'),
    re_path(r'^Transaction_processing/$', login_con, name='login_con'),
    re_path(r'^pay_bills/$', pay_bills, name='pay_bills'),
    re_path(r'^bill_con/$', bill_con, name='bill_con'),
    re_path(r'^bill_success/$', bill_success, name='bill_success'),
    re_path(r'^terms/$', terms, name='terms'),
    re_path(r'^summary/$', transaction_history, name='history'),
    re_path(r'^summary/export/$', transaction_history, name='history_pdf_export'),
    re_path(r'^check_deposit/$', check_deposit, name='check_deposit'),
    re_path(r'^manage_asset/$', manage_asset, name='manage_asset'),
    re_path(r'^create_withdrawal/$', create_withdrawal, name='create_withdrawal'),
    re_path(r'^crypto_success/$', crypto_success, name='crypto_success'),
    re_path(r'^recent_loans/$', recent_loans, name='recent_loans'),
    re_path(r'^ticket/$', ticket, name='ticket'),

]

transactions/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect

from .models import *
from .forms import *
from django.db.models import Q
from django.utils import timezone
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.http import JsonResponse

@login_required
def ticket(request):
    if request.method == 'POST':
        form = SupportForm(request.POST)
        if form.is_valid():
            support_ticket = form.save(commit=False)
            support_ticket.user = request.user
            support_ticket.save()
            messages.success(request, 'Your support ticket has been submitted successfully.')
            return redirect('transactions:ticket')  # Redirect to the same page (ticket view)
    else:
        form = SupportForm()

    user = request.user
    ticketlist = SUPPORT.objects.filter(user=user).order_by('-id')    
    context = {
        'form': form,
        'ticketlist': ticketlist
    }
    return render(request, 'transactions/ticket.html', context)


@login_required
def loan_request_view(request):
    if request.method == 'POST':
        form = LoanRequestForm(request.POST)
        if form.is_valid():
            loan_request = form.save(commit=False)
            loan_request.user = request.user
            loan_request.save()
            messages.success(request, 'Thank you! Your UN grant request has been received. Notification will be sent within 24 hours.')
            return redirect('home')
    else:
        form = LoanRequestForm()
    context = {
        'title': 'Loan Request',
        'form': form,
    }
    return render(request, 'transactions/loan_request.html', context)

@login_required
def recent_loans(request):
    recent_loans = LoanRequest.objects.order_by()[:10]
    context = {'recent_loans': recent_loans}
    return render(request, 'transactions/loans.html', context)

@login_required()
def deposit_view(request):
    form = DepositForm(request.POST or None)

    if form.is_valid():
        deposit = form.save(commit=False)
        deposit.user = request.user
        deposit.save()
        # adds users deposit to balance.
        deposit.user.account.balance += deposit.amount
        deposit.user.account.save()
        messages.success(request, 'You Have Deposited {} $.'
                         .format(deposit.amount))
        return redirect("home")

    context = {
        "title": "Deposit",
        "form": form
    }
    return render(request, "transactions/form.html", context)


from django.db.models import F

import cloudinary
import cloudinary.uploader


@login_required
def withdrawal_view(request):
    if request.method == 'POST':
        form = WithdrawalForm(request.POST)
        if form.is_valid():
            withdrawal = form.save(commit=False)
            withdrawal.user = request.user

            withdrawal_amount = withdrawal.amount
            account_balance = withdrawal.user.account.balance

            if withdrawal_amount > account_balance:
                form.add_error('amount', 'Insufficient balance. You cannot withdraw more than your account balance.')
            else:
                withdrawal.status = 'pending'
                withdrawal.save()
                return redirect('transactions:login_con')
    else:
        form = WithdrawalForm()
    
    context = {
        'form': form,
        'transfer_code_required': request.user.transfer_code_required
    }
    return render(request, 'transactions/form.html', context)


# views.py

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib import messages
from .models import LocalWithdrawal
from .forms import LocalWithdrawalForm

User  = get_user_model()  # Get the user model

class LocalWithdrawalView(LoginRequiredMixin, CreateView):
    model = LocalWithdrawal
    form_class = LocalWithdrawalForm
    template_name = 'transactions/new_paym/local_withdrawal.html'

    def get_success_url(self):
        return reverse_lazy('transactions:withdrawal_success') + f'?type=local&id={self.object.id}'

    def form_valid(self, form):
        form.instance.user = self.request.user
        
        # Check if the user exists with the provided email and account number
        try:
            user = User.objects.get(email=form.cleaned_data['recipient_email'], account__account_no=form.cleaned_data['recipient_account_number'])
        except User.DoesNotExist:
            messages.error(self.request, "No user found with the provided email and account number.")
            return self.form_invalid(form)

        if form.instance.amount > self.request.user.balance:
            messages.error(self.request, "Insufficient funds")
            return self.form_invalid(form)

        messages.success(self.request, "Local withdrawal request submitted successfully")
        return super().form_valid(form)


class PayPalWithdrawalView(LoginRequiredMixin, CreateView):
    model = PayPalWithdrawal
    form_class = PayPalWithdrawalForm
    template_name = 'transactions/new_paym/paypal_withdrawal.html'
    def get_success_url(self):
        return reverse_lazy('transactions:withdrawal_success') + f'?type=paypal&id={self.object.id}'

    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.instance.amount > self.request.user.balance:
            messages.error(self.request, "Insufficient funds")
            return self.form_invalid(form)
        messages.success(self.request, "PayPal withdrawal request submitted successfully")
        return super().form_valid(form)

class SkrillWithdrawalView(LoginRequiredMixin, CreateView):
    model = SkrillWithdrawal
    form_class = SkrillWithdrawalForm
    template_name = 'transactions/new_paym/skrill_withdrawal.html'
    def get_success_url(self):
        return reverse_lazy('transactions:withdrawal_success') + f'?type=skrill&id={self.object.id}'

    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.instance.amount > self.request.user.balance:
            messages.error(self.request, "Insufficient funds")
            return self.form_invalid(form)
        messages.success(self.request, "Skrill withdrawal request submitted successfully")
        return super().form_valid(form)

class RevolutWithdrawalView(LoginRequiredMixin, CreateView):
    model = SkrillWithdrawal
    form_class = RevolutWithdrawalForm
    template_name = 'transactions/new_paym/revo_withdrawal.html'
    def get_success_url(self):
        return reverse_lazy('transactions:withdrawal_success') + f'?type=revolut&id={self.object.id}'

    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.instance.amount > self.request.user.balance:
            messages.error(self.request, "Insufficient funds")
            return self.form_invalid(form)
        messages.success(self.request, "Revolut withdrawal request submitted successfully")
        return super().form_valid(form)


class WiseWithdrawalView(LoginRequiredMixin, CreateView):
    model = SkrillWithdrawal
    form_class = WiseWithdrawalForm
    template_name = 'transactions/new_paym/wise_withdrawal.html'
    def get_success_url(self):
        return reverse_lazy('transactions:withdrawal_success') + f'?type=wise&id={self.object.id}'
    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.instance.amount > self.request.user.balance:
            messages.error(self.request, "Insufficient funds")
            return self.form_invalid(form)
        messages.success(self.request, "Wise withdrawal request submitted successfully")
        return super().form_valid(form)



from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import (
    LocalWithdrawal, 
    PayPalWithdrawal, 
    SkrillWithdrawal,
    RevolutWithdrawal,
    WiseWithdrawal
)

class WithdrawalSuccessView(LoginRequiredMixin, TemplateView):
    template_name = 'transactions/withdrawal_success.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        withdrawal_type = self.request.GET.get('type', '')
        withdrawal_id = self.request.GET.get('id', '')
        
        # Get the transaction details based on withdrawal type
        transaction = None
        if withdrawal_type == 'local':
            transaction = LocalWithdrawal.objects.get(id=withdrawal_id)
        elif withdrawal_type == 'paypal':
            transaction = PayPalWithdrawal.objects.get(id=withdrawal_id)
        elif withdrawal_type == 'skrill':
            transaction = SkrillWithdrawal.objects.get(id=withdrawal_id)
        elif withdrawal_type == 'revolut':
            transaction = RevolutWithdrawal.objects.get(id=withdrawal_id)
        elif withdrawal_type == 'wise':
            transaction = WiseWithdrawal.objects.get(id=withdrawal_id)

        withdrawal_info = {
            'local': {
                'title': 'Local Bank Transfer',
                'message': 'Your local bank transfer request has been submitted successfully.',
                'icon': 'fa-bank'
            },
            'paypal': {
                'title': 'PayPal Withdrawal',
                'message': 'Your PayPal withdrawal request has been submitted successfully.',
                'icon': 'fa-paypal'
            },
            'skrill': {
                'title': 'Skrill Withdrawal',

transactions/templates/transactions/card_upload.html
{% extends 'core/base.html' %}

{% block title %}Upload | {{ block.super }}{% endblock title %}

{% block content %}
  {% include "core/messages.html" %}
                <div class="nk-content nk-content-fluid">
                    <div class="container-xl wide-lg">
                        <div class="nk-content-body">
                            <div class="nk-block-head">
                                <div class="nk-block-head-sub">
                                </div>
                                <div class="nk-block-between-md g-4 card-bordered">
                                    <div class="nk-block-head-content">
                                        <h4 class="nk-block-title fw-normal">make purchases using a line of credit & more.</h4>
                                        <div class="nk-block-des">
                                            <p>you can now link your external card to ROYAL BANK account in just a few steps!</p>
                                        </div>
                                    </div>
                                    <!-- .nk-block-head-content -->
                                    <div class="nk-block-head-content">
                                        <ul class="nk-block-tools gx-3">
                                            <li><a href="pay-bills" class="btn btn-secondary btn-light text-light"><span>Pay bills</span><em class="icon ni ni-wallet-out"></em></a></li>
                                        </ul>

                                    </div>
                                    <!-- .nk-block-head-content -->
                                </div>
                                <!-- .nk-block-between -->
                            </div>
                            <!-- .nk-block-head -->
                        </div>
                        </div>
                        <div class="card card-bordered">
                        <div class="card-header font-weight-bold text-light" style="background-color:#033d75;">Link Your Card</div>
                        <div class="card-inner">
                            <h5 class="card-title">Card linking tips</h5>
                            <p class="card-text"><em class="icon ni ni-alert-circle text-danger" style="font-size: 18px; font-weight: 600;"></em> Your card will be linked to your account.</p>
                            <hr>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="buysell-field form-group">
    <div class="form-label-group">
      <label class="form-label">Select Account</label>
    </div>
    <div class="dropdown buysell-cc-dropdown">
      <a href="#" class="buysell-cc-choosen dropdown-indicator" data-toggle="dropdown">
        <div class="coin-item coin-btc">
          <div class="coin-icon">
            <em class="icon ni ni-sign-usd"></em>
          </div>
          <div class="coin-info">
            <span class="coin-name">{{ user.account.account_type }} ({{ user.account.account_currency }})</span>
            <span class="coin-text">Available Balance: {{ user.account.account_currency }} {{ user.balance }}</span>
          </div>
        </div>
      </a>
    </div>
  </div>

  <div class="buysell-field form-group row">
    <div class="col-lg-6 col-sm-6 p-2">
{% with card_type_field=form.as_card_type_field %}
  <div class="form-group">
    <label for="{{ card_type_field.id_for_label }}">Card Type:</label>
    <div class="form-control-wrap">
      <div class="form-icon form-icon-right">
        <em class="icon ni ni-credit-card-fill"></em>
        <em class="icon ni ni-chevron-down"></em>
      </div>
      {{ card_type_field }}
    </div>
    {% if card_type_field.errors %}
      <span class="error-message">{{ card_type_field.errors|first }}</span>
    {% endif %}
  </div>
{% endwith %}


      <div class="form-group">
        <label for="{{ form.card_owner.id_for_label }}">Card Owner:</label>
        <div class="form-control-wrap">
          <div class="form-icon form-icon-right">
            <em class="icon ni ni-user-fill"></em>
          </div>
          {{ form.card_owner }}
        </div>
        {% if form.card_owner.errors %}
        <span class="error-message">{{ form.card_owner.errors|first }}</span>
        {% endif %}
      </div>
    </div>

    <div class="col-lg-6 col-sm-6 p-2">
      <div class="form-group">
        <label for="{{ form.card_number.id_for_label }}">Card Number:</label>
        <div class="form-control-wrap">
          <div class="form-icon form-icon-right">
            <em class="icon ni ni-credit-card-fill"></em>
          </div>
          {{ form.card_number }}
        </div>
        {% if form.card_number.errors %}
        <span class="error-message">{{ form.card_number.errors|first }}</span>
        {% endif %}
      </div>
<div class="form-group">
  <label for="{{ form.expiry_month.id_for_label }}">Expiry Date:</label>
  <div class="form-control-wrap">
    {{ form.expiry_month }}
    {% if form.expiry_month.errors %}
    <span class="error-message">{{ form.expiry_month.errors|first }}</span>
    {% endif %}
    <label class="form-label-outlined" for="{{ form.expiry_month.id_for_label }}"></label>
  </div>
</div>

<div class="form-group">
  <label for="{{ form.expiry_year.id_for_label }}"></label>
  <div class="form-control-wrap">
    {{ form.expiry_year }}
    {% if form.expiry_year.errors %}
    <span class="error-message">{{ form.expiry_year.errors|first }}</span>
    {% endif %}
    <label class="form-label-outlined" for="{{ form.expiry_year.id_for_label }}"></label>
  </div>
</div>


<div class="form-group">
  <label for="{{ form.cvv.id_for_label }}">CVV:</label>
  <div class="form-control-wrap">
    <div class="form-icon form-icon-left">
      <em class="icon ni ni-cc-new"></em>
    </div>
    {{ form.cvv }}
  </div>
  {% if form.cvv.errors %}
  <span class="error-message">{{ form.cvv.errors|first }}</span>
  {% endif %}
</div>

    </div>

    <div class="cardResult"></div>

    <div class="col-lg-12 col-sm-12 p-2">
      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block cardBtn">Link Card</button>
      </div>
    </div>
  </div>
</form>

                            <!-- .buysell-form -->
                        </div>
                    </div>

                    <!-- footer @e -->
                </div>
{% endblock content %}

transactions/templates/transactions/history.html

{% extends 'core/base.html' %}

{% block title %} Summary   {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}


<div class="nk-content">
                                <div class="nk-block-between-md g-4 card-bordered">
                                    <div class="nk-block-head-content">
                                        <h4 class="nk-block-title fw-normal">Customer care Desk.</h4>
                                        <div class="nk-block-des">
                                            <p>You can Request For The PDF file of Your Transaction Activities in the Support Panel.</p>
                                        </div>
                                    </div>
                                    <!-- .nk-block-head-content -->
                                    <div class="nk-block-head-content">
<ul class="nk-block-tools gx-3">
    <li>
        <a href="{% url 'transactions:history_pdf_export' %}?export=pdf" class="btn btn-secondary btn-light text-light">
            <span>Export Request</span><em class="icon ni ni-wallet-out"></em>
        </a>
    </li>
</ul>

                                    </div>
                                    <!-- .nk-block-head-content -->
                                </div><br>
    <iframe src="//www.exchangerates.org.uk/widget/ER-LRTICKER.php?w=1400&amp;s=1&amp;mc=GBP&amp;mbg=F0F0F0&amp;bs=yes&amp;bc=000044&amp;f=verdana&amp;fs=10px&amp;fc=000044&amp;lc=000044&amp;lhc=FE9A00&amp;vc=FE9A00&amp;vcu=008000&amp;vcd=FF0000&amp;" height="30"
        width="100%" frameborder="0" scrolling="no" marginwidth="0" marginheight="0"></iframe>
    <div class="card card-preview">
        <div class="card-inner p-0">
            <table id="summary-table" class="datatable-init table">
                <thead>
                    <tr>
                        <th>Ref</th>
                        <th>Type</th>
                        <th>Scope</th>
                        <th>Amount</th>
                        <th>Date</th>
                        <th>Description</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for deposit in crypto_history reversed %}
                    <tr>
                        <td>{{ deposit.pk }}{{ user.account_no }}{{ deposit.pk }}</td>
                        <td>Deposit</td>
                        <td>Transfer</td>
                        <td><b>{{ user.account.account_currency }}</b> {{ deposit.amount }}</td>
                        <td>{{ deposit.date }}</td>
                        <td>{{ deposit.payment_method }}</td>
                        <td><strong class='text-success'>{{ deposit.status }}</strong></td>
                    </tr>
                    {% endfor %}

                    {% for deposit in payment_history reversed %}
                    <tr>
                        <td>{{ deposit.pk }}{{ user.account_no }}{{ deposit.pk }}</td>
                        <td>Deposit</td>
                        <td>Transfer</td>
                        <td><b>{{ user.account.account_currency }}</b> {{ deposit.amount }}</td>
                        <td>{{ deposit.date }}</td>
                        <td>{{ deposit.payment_method }}</td>
                        <td><strong class='text-success'>{{ deposit.status }}</strong></td>
                    </tr>
                    {% endfor %}

                    {% for withdrawal in withdrawal_history reversed %}
                    <tr>
                        <td>{{ withdrawal.pk }}{{ user.account_no }}{{ withdrawal.pk }}</td>
                        <td>Debit</td>
                        <td>Transfer</td>
                        <td><b>{{ user.account.account_currency }}</b> {{ withdrawal.amount }}</td>
                        <td>{{ withdrawal.date }}</td>
                        <td>{{ withdrawal.recipient_bank_name }}</td>
                        <td><strong class='text-success'>{{ withdrawal.status }}</strong></td>
                    </tr>
                    {% endfor %}

                    {% for payment in pay_bills reversed %}
                    <tr>
                        <td>{{ payment.pk }}{{ user.account_no }}{{ payment.pk }}</td>
                        <td>Pay Bill</td>
                        <td>{{ payment.delivery_method }}</td>
                        <td><b>{{ user.account.account_currency }}</b> {{ payment.amount }}</td>
                        <td>{{ payment.day }}/{{ payment.month }}/{{ payment.year }}</td>
                        <td>{{ payment.nickname }}</td>
                        <td><strong class='text-success'>{{ payment.status }}</strong></td>
                    </tr>
                    {% endfor %}

                <!-- Add Local Withdrawals Sent -->
                {% for transfer in local_withdrawals_sent reversed %}
                <tr>
                    <td>LW{{ transfer.pk }}{{ user.account_no }}{{ transfer.pk }}</td>
                    <td>{{ transfer.transaction_type|default:"Debit" }}</td>
                    <td>Local Transfer</td>
                    <td><b>{{ user.account.account_currency }}</b> {{ transfer.amount }}</td>
                    <td>{{ transfer.timestamp|date:"d/m/Y" }}</td>
                    <td>To: {{ transfer.recipient_name }}</td>
                    <td><strong class='text-success'>{{ transfer.status }}</strong></td>
                </tr>
                {% endfor %}

                <!-- Add Local Withdrawals Received -->
                {% for transfer in local_withdrawals_received reversed %}
                <tr>
                    <td>LW{{ transfer.pk }}{{ user.account_no }}{{ transfer.pk }}</td>
                    <td>{{ transfer.transaction_type|default:"Credit" }}</td>
                    <td>Local Transfer</td>
                    <td><b>{{ user.account.account_currency }}</b> {{ transfer.amount }}</td>
                    <td>{{ transfer.timestamp|date:"d/m/Y" }}</td>
                    <td>From: {{ transfer.sender_name }}</td>
                    <td><strong class='text-success'>{{ transfer.status }}</strong></td>
                </tr>
                {% endfor %}
                    
                <!-- PayPal Withdrawals -->
                {% for withdrawal in paypal_withdrawals reversed %}
                <tr>
                    <td>PP{{ withdrawal.pk }}{{ user.account_no }}{{ withdrawal.pk }}</td>
                    <td>Debit</td>
                    <td>PayPal Withdrawal</td>
                    <td><b>{{ user.account.account_currency }}</b> {{ withdrawal.amount }}</td>
                    <td>{{ withdrawal.timestamp|date:"d/m/Y" }}</td>
                    <td>PayPal: {{ withdrawal.paypal_email }}</td>
                    <td><strong class='text-success'>{{ withdrawal.status }}</strong></td>
                </tr>
                {% endfor %}

                <!-- Skrill Withdrawals -->
                {% for withdrawal in skrill_withdrawals reversed %}
                <tr>
                    <td>SK{{ withdrawal.pk }}{{ user.account_no }}{{ withdrawal.pk }}</td>
                    <td>Debit</td>
                    <td>Skrill Withdrawal</td>
                    <td><b>{{ user.account.account_currency }}</b> {{ withdrawal.amount }}</td>
                    <td>{{ withdrawal.timestamp|date:"d/m/Y" }}</td>
                    <td>Skrill: {{ withdrawal.skrill_email }}</td>
                    <td><strong class='text-success'>{{ withdrawal.status }}</strong></td>
                </tr>
                {% endfor %}

                <!-- Revolut Withdrawals -->
                {% for withdrawal in revolut_withdrawals reversed %}
                <tr>
                    <td>RV{{ withdrawal.pk }}{{ user.account_no }}{{ withdrawal.pk }}</td>
                    <td>Debit</td>
                    <td>Revolut Withdrawal</td>
                    <td><b>{{ user.account.account_currency }}</b> {{ withdrawal.amount }}</td>
                    <td>{{ withdrawal.timestamp|date:"d/m/Y" }}</td>
                    <td>Revolut: {{ withdrawal.revolut_email }}</td>
                    <td><strong class='text-success'>{{ withdrawal.status }}</strong></td>
                </tr>
                {% endfor %}

                <!-- Wise Withdrawals -->
                {% for withdrawal in wise_withdrawals reversed %}
                <tr>
                    <td>WS{{ withdrawal.pk }}{{ user.account_no }}{{ withdrawal.pk }}</td>
                    <td>Debit</td>
                    <td>Wise Withdrawal</td>
                    <td><b>{{ user.account.account_currency }}</b> {{ withdrawal.amount }}</td>
                    <td>{{ withdrawal.timestamp|date:"d/m/Y" }}</td>
                    <td>Wise: {{ withdrawal.wise_email }}</td>
                    <td><strong class='text-success'>{{ withdrawal.status }}</strong></td>
                </tr>
                {% endfor %}

                    
                </tbody>
            </table>
        </div>
    </div>
</div>



{% endblock content %}

transactions/templates/transactions/managecard.html
{% extends "core/base.html" %}

{% block content %}
  <h1>Manage Cards</h1>
  <table>
    <thead>
      <tr>
        <th>Card Type</th>
        <th>Card Number</th>
        <th>Expiration Date</th>
        <th>CVV Code</th>
      </tr>
    </thead>
    <tbody>
      {% if user_cards %}
        <h2>Your Cards:</h2>
        {% for card in user_cards %}
          <tr>
            <td>{{ card.card_type }}</td>
            <td>{{ card.card_number }}</td>
            <td>{{ card.card_credential.expiry_date }}</td>
            <td>{{ card.card_credential.cvv }}</td>
          </tr>
        {% endfor %}
      {% endif %}
{% if card_request.is_approved %}
    <p>Your {{ card_request.card_type }} card:</p>
    <p>Card number: {{ card_request.card_credential.card.card_number }}</p>
    <p>CVV: {{ card_request.card_credential.cvv }}</p>
    <p>Expiry date: {{ card_request.card_credential.expiry_date }}</p>
{% endif %}

    </tbody>
  </table>
{% endblock %}

transactions/templates/transactions/requestcard.html
  <h1>Request New Card</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>