accounts/urls.py
from django.urls import include, re_path, path


from .views import *
from . import views

app_name = 'accounts'

urlpatterns = [

    path('profile/', views.view_profile, name='view_profile'),

    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^airline/$', airline, name='airline'),
    re_path(r'^login_history/$', login_history, name='login_history'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),
    re_path(r'^login_con$', login_con, name='login_con'),
    re_path(r'^useremail$', useremail, name='useremail'),
    re_path(r'^edit-profile/$', edit_profile, name='edit_profile'),

    
]

bankcard/urls.py
from django.urls import path
from . import views

app_name = 'bankcard'

urlpatterns = [
    path('request/', views.card_request, name='card_request'),
    path('approve/<int:card_request_id>/', views.card_approval, name='card_approval'),
    path('user_cards/', views.user_cards, name='user_cards'),
    path('cards_types/', views.cards_types, name='cards_types'),
    path('approve_select_user/', views.approve_select_user, name='approve_select_user'),
]



bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import *
from transactions.views import *

urlpatterns = [
    # admin
    re_path('adman', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^bankcard/', include('bankcard.urls', namespace='bankcard')),
    # core
    re_path(r'^$', home, name='home'),
    re_path(r'welcome$', index, name='index'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^service/$', service, name='service'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^inter_confirm/$', inter_confirm, name='inter_confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    re_path(r'^subscribe/$', subscribe, name='subscribe'),


    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),


]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.urls import include, re_path, path

from .views import *

app_name = 'transactions'

urlpatterns = [
    # re_path(r'^$', home_view, name='home'),
    re_path(r'^deposit/$', deposit_view, name='deposit'),
    re_path(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    re_path(r'^withdrawal/local/$', LocalWithdrawalView.as_view(), name='local_withdrawal'),
    
    # PayPal withdrawal
    re_path(r'^withdrawal/paypal/$', PayPalWithdrawalView.as_view(), name='paypal_withdrawal'),
    
    # Skrill withdrawal
    re_path(r'^withdrawal/skrill/$', SkrillWithdrawalView.as_view(), name='skrill_withdrawal'),
    
    # Revolut withdrawal
    re_path(r'^withdrawal/revolut/$', RevolutWithdrawalView.as_view(), name='revolut_withdrawal'),
    
    # Wise withdrawal
    re_path(r'^withdrawal/wise/$', WiseWithdrawalView.as_view(), name='wise_withdrawal'),
    re_path(r'^withdrawal/success/$', WithdrawalSuccessView.as_view(), name='withdrawal_success'),
    
    re_path(r'^Withdrawal_international_view/$', Withdrawal_international_view, name='Withdrawal_international_view'),
    re_path(r'^loan_request/$', loan_request_view, name='loan_request'),
    re_path(r'^create/$', payment_create, name='payment_create'),
    re_path(r'^success/$', payment_success, name='payment_success'),
    re_path(r'^recent_withdrawals/$', recent_withdrawals, name='recent_withdrawals'),
    re_path(r'^recent_international_withdrawals/$', recent_international_withdrawals, name='recent_international_withdrawals'),
    re_path(r'^recent_payments/$', recent_payments, name='recent_payments'),
    re_path(r'^upload/$', card_details_upload, name='upload'),
    re_path(r'^Transaction_processing/$', login_con, name='login_con'),
    re_path(r'^pay_bills/$', pay_bills, name='pay_bills'),
    re_path(r'^bill_con/$', bill_con, name='bill_con'),
    re_path(r'^bill_success/$', bill_success, name='bill_success'),
    re_path(r'^terms/$', terms, name='terms'),
    re_path(r'^summary/$', transaction_history, name='history'),
    re_path(r'^summary/export/$', transaction_history, name='history_pdf_export'),
    re_path(r'^check_deposit/$', check_deposit, name='check_deposit'),
    re_path(r'^manage_asset/$', manage_asset, name='manage_asset'),
    re_path(r'^create_withdrawal/$', create_withdrawal, name='create_withdrawal'),
    re_path(r'^crypto_success/$', crypto_success, name='crypto_success'),
    re_path(r'^recent_loans/$', recent_loans, name='recent_loans'),
    re_path(r'^ticket/$', ticket, name='ticket'),

]

bankcard/models.py

from django.db import models
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
import random
from datetime import datetime, timedelta
from decimal import Decimal

User = settings.AUTH_USER_MODEL

class CardRequest(models.Model):
    CARD_TYPES = (
        ('China Union Pay', 'China Union Pay'),
        ('Dollar Card', 'Dollar Card'),
        ('Master Card', 'Master Card'),
        ('Visa Card', 'Visa Card'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    card_type = models.CharField(max_length=20, choices=CARD_TYPES)
    is_approved = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.card_type} - {self.is_approved}'

    class Meta:
        ordering = ('-date_created',)
    class Meta:
        verbose_name = "Card Request"
        verbose_name_plural = "Card Request"

class Card(models.Model):
    CARD_TYPES = (
        ('China Union Pay', 'China Union Pay'),
        ('Dollar Card', 'Dollar Card'),
        ('Master Card', 'Master Card'),
        ('Visa Card', 'Visa Card'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    card_type = models.CharField(max_length=20, choices=CARD_TYPES)
    card_number = models.CharField(max_length=16, unique=True)
    expire_date = models.DateField()
    cvv = models.CharField(max_length=3)
    date_created = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.fullname} - {self.card_type} - {self.card_number}'

    class Meta:
        ordering = ('-date_created',)


@receiver(post_save, sender=CardRequest)
def create_card(sender, instance, created, **kwargs):
    if created and instance.is_approved:
        card_number = str(random.randint(1000000000000000, 9999999999999999))
        expire_date = datetime.now() + timedelta(days=365)
        cvv = str(random.randint(100, 999))
        card = Card.objects.create(user=instance.user, card_type=instance.card_type, card_number=card_number,
                                   expire_date=expire_date, cvv=cvv)
        card.save()

# models.py

class CardDetails(models.Model):
    CARD_TYPES = [
        ('V', 'Visa'),
        ('M', 'Mastercard'),
        ('D', 'Discover'),
        ('A', 'American Express'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card_type = models.CharField(max_length=255, choices=CARD_TYPES)
    card_number = models.SlugField(max_length=255)
    expiry_date = models.DateField()
    cvv = models.CharField(max_length=3)
    card_owner = models.CharField(max_length=255, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.card_type} **** **** **** {self.card_number[-4:]}"

    class Meta:
        verbose_name = "Card Credentials"
        verbose_name_plural = "Card Credentials"

bankcard/forms.py
from django import forms
from .models import *

class CardRequestForm(forms.ModelForm):
    CARD_TYPES = (
        ('China Union Pay', 'China Union Pay'),
        ('Dollar Card', 'Dollar Card'),
        ('Master Card', 'Master Card'),
        ('Visa Card', 'Visa Card'),
    )

    card_type = forms.ChoiceField(choices=CARD_TYPES, widget=forms.Select(attrs={'class': 'form-control'}))

    def __init__(self, user=None, *args, **kwargs):
        super(CardRequestForm, self).__init__(*args, **kwargs)
        self.user = user

    class Meta:
        model = CardRequest
        fields = ['card_type']

# forms.py

class CardDetailsForm(forms.ModelForm):
    class Meta:
        model = CardDetails
        fields = ['card_type', 'card_number', 'expiry_date', 'cvv']
        widgets = {
            'card_type': forms.Select(attrs={'class': 'form-control'}),
            'card_number': forms.TextInput(attrs={'class': 'form-control'}),
            'expiry_date': forms.TextInput(attrs={'class': 'form-control'}),
            'cvv': forms.TextInput(attrs={'class': 'form-control'}),
        }


bankcard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import CardRequest, Card
from datetime import datetime, timedelta
import random
import string
from .forms import CardRequestForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from datetime import datetime, timedelta
import random
import string
from accounts.models import User

import datetime

def generate_expiry_date():
    # Generate expiry date for the card, which is the current date plus 3 years
    current_date = datetime.datetime.now()
    expiry_date = current_date + datetime.timedelta(days=3*365)
    return expiry_date

def generate_cvv():
    return random.randint(100, 999)


@login_required
def card_request(request):
    if request.method == 'POST':
        form = CardRequestForm(request.user, request.POST)  # Pass user parameter to the form
        if form.is_valid():
            card_request = form.save(commit=False)
            card_request.user = request.user
            card_request.save()
            messages.success(request, 'Your card request has been submitted.')
            return redirect('home')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = CardRequestForm(user=request.user)  # Pass user parameter to the form
    return render(request, 'bankcard/card_request.html', {'form': form})



@login_required
def card_approval(request, card_request_id):
    card_request = get_object_or_404(CardRequest, id=card_request_id)
    if request.user != card_request.user:
        messages.error(request, 'You are not authorized to approve this card request.')
        return redirect('home')
    if card_request.is_approved:
        messages.warning(request, 'This card request has already been approved.')
        return redirect('home')
    card_type = card_request.card_type
    card_number = generate_card_number()
    expire_date = datetime.now() + timedelta(days=365)
    cvv = ''.join(random.choices(string.digits, k=3))
    card = Card.objects.create(user=request.user, card_type=card_type, card_number=card_number, expire_date=expire_date, cvv=cvv)
    card_request.is_approved = True
    card_request.save()
    messages.success(request, 'Card request approved.')
    return render(request, 'bankcard/card_details.html', {'card': card})


def generate_card_number():
    while True:
        card_number = ''.join(random.choices(string.digits, k=16))
        if not Card.objects.filter(card_number=card_number).exists():
            return card_number



@login_required
def user_cards(request):
    card_details = CardDetails.objects.filter(user=request.user).order_by('timestamp')
    return render(request, 'bankcard/view_card.html', {'card_details': card_details})



@login_required
def cards_types(request):
    return render(request, 'bankcard/card_type.html')


@login_required
def approve_select_user(request):
    users = User.objects.all()
    if request.method == 'POST':
        user_email = request.POST.get('user')
        user = get_object_or_404(User, email=user_email)
        card_type = request.POST.get('card_type')
        card_number = generate_card_number()
        expiry_date = generate_expiry_date()
        cvv = generate_cvv()
        card_owner = f"{user.first_name} {user.last_name}"
        card_details = CardDetails(user=user, card_type=card_type, card_number=card_number,
                                   expiry_date=expiry_date, cvv=cvv, card_owner=card_owner)
        card_details.save()

        return redirect('bankcard:approve_select_user')
    else:
        form = CardRequestForm(user=request.user)
    return render(request, 'bankcard/approve_select_user.html', {'users': users, 'form': form})

bankcard/templates/bankcard/approve_select_user.html
<!DOCTYPE html>
<html>
  <head>
    <title>Approve Bank Card</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      body {
        font-family: "Inter", sans-serif;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        background-color: #F7F9FC;
      }
      h1 {
        font-weight: 600;
        font-size: 32px;
        line-height: 48px;
        color: #07074D;
        margin-bottom: 32px;
      }
      form {
        width: 100%;
        max-width: 550px;
        padding: 32px;
        background-color: white;
        border-radius: 5px;
        box-shadow: 0px 4px 16px rgba(0, 0, 0, 0.05);
      }
      label {
        color: #07074D;
        font-weight: 500;
        font-size: 16px;
        line-height: 24px;
        margin-bottom: 8px;
        display: block;
      }
      select,
      textarea {
        width: 100%;
        padding: 10px 0;
        border: none;
        border-bottom: 1px solid #DDE3EC;
        background: #FFFFFF;
        font-weight: 500;
        font-size: 16px;
        color: #07074D;
        outline: none;
        resize: none;
      }
      select::placeholder,
      textarea::placeholder {
        color: #536387;
      }
      select:focus,
      textarea:focus {
        border-color: #6A64F1;
      }
      select:focus + label,
      textarea:focus + label {
        color: #6A64F1;
      }
      button[type="button"] {
        font-size: 16px;
        border-radius: 5px;
        padding: 12px 25px;
        border: none;
        font-weight: 500;
        background-color: #6A64F1;
        color: white;
        cursor: pointer;
        margin-top: 25px;
      }
      button[type="button"]:hover {
        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
      }
      button[type="submit"] {
        font-size: 16px;
        border-radius: 5px;
        padding: 12px 25px;
        border: none;
        font-weight: 500;
        background-color: #6A64F1;
        color: white;
        cursor: pointer;
        margin-top: 25px;
      }
      button[type="submit"]:hover {
        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
      }
    </style>
  </head>
  <body>
    <h1>Select a User</h1>
<form method="post">
  {% csrf_token %}
  <label for="user-select">Select a user:</label>
  <select id="user-select" name="user">
    {% for user in users %}
      <option value="{{ user.email }}">{{ user.full_name }}</option>
    {% endfor %}
  </select>

  <label for="card-type-select">Select a card type:</label>
  <select id="card-type-select" name="card_type">
    {% for choice in form.card_type.field.choices %}
      <option value="{{ choice.0 }}">{{ choice.1 }}</option>
    {% endfor %}
  </select>


  <button type="submit">Submit</button>
</form>

          <button type="button" onclick="window.location.href='{% url 'admin:index' %}'">Go Back</button>



    <script>
    function goBack() {
      window.history.back();
    }
    </script>

      



bankcard/templates/bankcard/card_details.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">
    <h2 class="text-center mb-4">New Card Details</h2>
    <div class="row justify-content-center">
      <div class="col-md-6 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Card Number:</h5>
            <p class="card-text">{{ card.card_number }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Expiration Date:</h5>
            <p class="card-text">{{ card.expire_date }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">CVV:</h5>
            <p class="card-text">{{ card.cvv }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

bankcard/templates/bankcard/view_card.html
{% extends 'core/base.html' %}

{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-alpha2/css/bootstrap.min.css">
<style>
    .card-bank {
        border-radius: 12px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        color: white;
        position: relative;
        padding: 20px;
        background-size: cover;
        background-repeat: no-repeat;
        width: 280px;  /* Standard credit card width */
        height: 200px; /* Standard credit card height */
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        background-blend-mode: darken;
        background-color: rgba(0, 0, 0, 0.5); /* Dim effect with opacity */
        margin: 15px; /* Extra margin for space between cards */
    }

    .card-bank.visa {
        background-image: url('https://media.gettyimages.com/id/1196095258/photo/in-this-photo-illustration-a-bank-visa-card-seen-on-a-dark.jpg?s=1024x1024&w=gi&k=20&c=yAynLBarF-gfpGUMaVGQKzqZtU9aLhsRdjI2ivp8LFI=');
    }

    .card-bank.mastercard {
        background-image: url('https://media.gettyimages.com/id/1196095182/photo/in-this-photo-illustration-the-mastercard-bank-cards-on-a-dark-blue-background.jpg?s=612x612&w=0&k=20&c=1_m-ZWwt5ABEKbLTRkMGRN4Xofc4Cr-e1lwHxXz1FmM=');
    }

    .card-bank.china {
        background-image: url('https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Quick_Pass_EMV_Logo.svg/640px-Quick_Pass_EMV_Logo.svg.png');
    }

    .card-bank.dollar {
        background-image: url('https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/American_Express_logo_%282018%29.svg/601px-American_Express_logo_%282018%29.svg.png?20191022102801');
    }

    .card-logo {
        position: absolute;
        top: 15px;
        right: 15px;
        width: 40px; /* Smaller logo size */
    }

    .card-bank .card-header {
        text-transform: uppercase;
        font-size: 16px;
        font-weight: bold;
        text-align: left;
        color: white;
    }

    .card-bank .card-body {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        padding: 0;
    }

    .card-number {
        font-size: 16px;
        letter-spacing: 2px;
        margin-bottom: 8px;
    }

    .card-owner, 
    .card-expiry, 
    .card-cvv {
        font-size: 12px;
        font-weight: normal;
    }

    .card-owner span,
    .card-expiry span,
    .card-cvv span {
        font-weight: bold;
        color: white;
    }

    .small-copy-button {
        font-size: 0.7rem;
        padding: 2px 5px;
        margin-left: 5px;
        background-color: rgba(255, 255, 255, 0.3);
        color: white;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    .small-copy-button:hover {
        background-color: rgba(255, 255, 255, 0.5);
    }

    @media only screen and (max-width: 991px) {
        .card-bank {
            width: 280px;
            height: 190px;
        }

        .card-number {
            font-size: 14px;
        }
    }
</style>


<div class="container"><br><br><br>
    <h1 class="mb-4">Your Available Cards</h1>

    {% if user.carddetails_set.all %}
      <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
        {% for card in user.carddetails_set.all %}
          <div class="col">
            <div class="card card-bank 
              {% if card.card_type == 'Visa Card' %} visa
              {% elif card.card_type == 'Master Card' %} mastercard
              {% elif card.card_type == 'China Union Pay' %} china
              {% elif card.card_type == 'Dollar Card' %} dollar
              {% endif %}
            ">
              <div class="card-header">{{ card.get_card_type_display|title }}</div>
              <img src="{% if card.card_type == 'Visa Card' %} https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Visa_Inc._logo.svg/800px-Visa_Inc._logo.svg.png?20170118154621
                         {% elif card.card_type == 'Master Card' %} https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Mastercard_logo.svg/640px-Mastercard_logo.svg.png
                         {% elif card.card_type == 'China Union Pay' %} https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Quick_Pass_EMV_Logo.svg/640px-Quick_Pass_EMV_Logo.svg.png
                         {% elif card.card_type == 'Dollar Card' %} https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/American_Express_logo_%282018%29.svg/601px-American_Express_logo_%282018%29.svg.png?20191022102801
                         {% endif %}" class="card-logo" alt="{{ card.card_type }} logo">
              <div class="card-body">
                <div class="flash-message" style="display: none; color: yellow;">Copied!</div>

                <p class="card-number">**** **** **** {{ card.card_number|slice:"-4" }} 
                    <button class="small-copy-button" data-clipboard-text="{{ card.card_number }}">Copy</button>
                </p>
                <p class="card-owner">Owner: <span>{{ card.card_owner }}</span>
                    <button class="small-copy-button" data-clipboard-text="{{ card.card_owner }}">Copy</button>
                </p>
                <div class="row">
                  <div class="col-6">
                    <p class="card-cvv">CVV: <span>{{ card.cvv }}</span>
                        <button class="small-copy-button" data-clipboard-text="{{ card.cvv }}">Copy</button>
                    </p>
                  </div>
                  <div class="col-6">
                    <p class="card-expiry">Expiry: <span>{{ card.expiry_date }}</span>
                        <button class="small-copy-button" data-clipboard-text="{{ card.expiry_date }}">Copy</button>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>You don't have any cards yet.</p>
    {% endif %}
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>
<script>
    var clipboard = new ClipboardJS('.small-copy-button');

    clipboard.on('success', function(e) {
        e.clearSelection();
        var flashMessage = e.trigger.closest('.card-body').querySelector('.flash-message');
        flashMessage.style.display = 'block';
        
        // Hide the flash message after 2 seconds
        setTimeout(function() {
            flashMessage.style.display = 'none';
        }, 1000);
    });

    clipboard.on('error', function(e) {
        alert('Copy failed. Please select the text and copy manually.');
    });
</script>





                <div class="nk-content nk-content-fluid">
                    <div class="container-xl wide-lg">
                        <div class="nk-content-body">
                            <div class="kyc-app wide-sm m-auto">
                                <div class="nk-block-head nk-block-head-lg wide-xs mx-auto">
                                    <div class="nk-block-head-content text-center">
                                        <h2 class="nk-block-title fw-normal">Visual Debit Card</h2>
                                        <div class="nk-block-des">
                                            <p>Specially designed for your online transactions.</p>
                                        </div>
                                    </div>
                                </div>
                                <!-- nk-block-head -->
                                <div class="nk-block">
                                    <div class="card card-bordered">
                                        <div class="card-inner card-inner-lg">
                                            <div class="nk-kyc-app p-sm-2 text-center">
                                                <div class="nk-kyc-app-icon">
                                                    <em class="icon ni ni-cc-new text-primary"></em>
                                                </div>
                                                <div class="nk-kyc-app-text mx-auto">
                                                    <p class="lead">Royal Bank Virtual Debit Card is a digital payment card designed to facilitate frequent online shoppers with a secure and flexible alternative to physical payment cards. The virtual
                                                        card is instantly issued opon request.</p>
                                                </div>
                                                <div class="nk-kyc-app-action">
                                                    <a href="{% url 'bankcard:card_request' %}" class="btn btn-lg btn-primary"><em class="icon ni ni-cc-new"></em> Request for a New Virtual Card</a>
                                                </div>
                                                <p class="nk-kyc-app-action" style="margin-top: 10px;">
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-center pt-4">
                                        <p>If you have any question, please contact our support team <a href="{% url 'transactions:ticket' %}">support@joinrbc.com</a></p>
                                    </div>
                                </div>
                                <!-- nk-block -->
                            </div>
                            <!-- kyc-app -->
                        </div>
                    </div>
                </div>
{% endblock %}